const data = {
    products: [
        {
            _id:'1',
            name: 'Iphone 11',
            category: 'Phones',
            image: '/images/iphone11-negro.jpg',
            price: 120000,
            brand: 'Apple',
            rating: 4.5,
            numReviews: 10,
            description: 'Iphone 128Gb - Negro - Nuevo en caja cerrada y sellada',
        },
        {
            _id:'2',
            name: 'Iphone 11',
            category: 'Phones',
            image: '/images/iphone11-blanco.jpg',
            price: 120000,
            brand: 'Apple',
            rating: 4.5,
            numReviews: 10,
            description: 'Iphone 128Gb - Blanco - Nuevo en caja cerrada y sellada',
        },
        {
            _id:'3',
            name: 'Samsung Galaxy S20FE',
            category: 'Phones',
            image: '/images/samsung-s20fe.jpg',
            price: 140000,
            brand: 'Samsung',
            rating: 4.5,
            numReviews: 10,
            description: 'Samsung S20EF 128Gb - Gris - Nuevo en caja cerrada y sellada',
        },
        {
            _id:'4',
            name: 'Samsung Galaxy Note 20 Ultra',
            category: 'Phones',
            image: '/images/samsung-note20ultra.jpg',
            price: 120000,
            brand: 'Samsung',
            rating: 4.5,
            numReviews: 10,
            description: 'Samsung Note 20 Utra 256Gb - Dorado - Nuevo en caja cerrada y sellada',
        },
        {
            _id:'5',
            name: 'Samsung A51',
            category: 'Phones',
            image: '/images/samsung-A51.jpg',
            price: 45000,
            brand: 'Samsung',
            rating: 4.5,
            numReviews: 10,
            description: 'Samsung A51 128Gb - Negro - Nuevo en caja cerrada y sellada',
        },
        {
            _id:'6',
            name: 'Samsung Galaxy ZFlip',
            category: 'Phones',
            image: '/images/samsung-zflip.jpg',
            price: 140000,
            brand: 'Samsung',
            rating: 4.5,
            numReviews: 10,
            description: 'Samsung ZFlip 256Gb - Purpura - Nuevo en caja cerrada y sellada',
        },
    ],
};

export default data;